### PR TITLE
Fix #18: Prevent division by zero exception

### LINKED ISSUE #18: Submitting empty phpunit report kills the script
Submitting a phpunit clover report from Travis CI with no unit tests will kill the script.

PHP Warning: Division by zero in /home/travis/build/bblue/ruby/vendor/codacy/coverage/src/Codacy/Coverage/Parser/CloverParser.php on line 28

### PR DESCRIPTION
**Pull request by mrfyda**
Fixes #18

### CODE REVIEW

File: src/Codacy/Coverage/Parser/CloverParser.php [hunk 1]
```diff
@@ -135,4 +135,12 @@ private function getRelativePath(\SimpleXMLElement $fileName)
 
         return $str;
     }
+
+    private function safeDivision($a, $b)
```
Comment (mrfyda) [inline src/Codacy/Coverage/Parser/CloverParser.php]: Codacy Issue found: [Avoid unused private methods such as 'safeDivision'.](https://www.codacy.com/app/Codacy/php-codacy-coverage/file/1718512815/issues/source?bid=2159630&fileBranchId=3050296#l139)

Comment (mrfyda) [inline src/Codacy/Coverage/Parser/CloverParser.php]: Codacy Issue found: [Avoid variables with short names like $a. Configured minimum length is 3.](https://www.codacy.com/app/Codacy/php-codacy-coverage/file/1718512815/issues/source?bid=2159630&fileBranchId=3050296#l139)

Comment (mrfyda) [inline src/Codacy/Coverage/Parser/CloverParser.php]: Codacy Issue found: [Avoid variables with short names like $a. Configured minimum length is 3.](https://www.codacy.com/app/Codacy/php-codacy-coverage/file/1728433202/issues/source?bid=2159630&fileBranchId=3050296#l139)
